### ISSUE TITLE
Try newest version (1.3.7+) of `ExParameterized` and confirm whether it resolves "invalid quoted expression" error

### ISSUE THREAD

**Issue by kenny-evitt** [kenny-evitt/ex_parameterized#1]
The original "invalid quoted expression" error issue:

 - ["invalid quoted expression" compile error for a tuple value containing a list · Issue #35 · KazuCocoa/ex_parameterized](https://github.com/KazuCocoa/ex_parameterized/issues/35)

**Comment by nCrazed** [comment]
Running into a related problem while using 1.3.7:

```elixir
defmodule ReproTest do
  use ExUnit.Case
  use ExUnit.Parameterized

  test_with_params "reproduce",
                   fn _ ->
                     assert true
                   end do
    [
      {[%{}]}
    ]
  end
end
```

```
 == Compilation error in file test/repro_test.exs ==
 ** (CompileError) test/repro_test.exs: invalid quoted expression: %{}
 
 Please make sure your quoted expressions are made of valid AST nodes. If you would like to introduce a value into the AST, such as a four-element tuple or a map, make sure to call Macro.escape/1 before
     (stdlib 3.16.1) lists.erl:1358: :lists.mapfoldl/3
     (stdlib 3.16.1) lists.erl:1359: :lists.mapfoldl/3
     test/repro_test.exs:5: (module)
     (stdlib 3.16.1) erl_eval.erl:685: :erl_eval.do_apply/6
```

**Comment by kenny-evitt** [comment]
@nCrazed This is just a private fork – I don't have the 'personal bandwidth' to offer any support. (I also haven't added any commits to this repo either.)

I created this issue as a personal 'todo', and I don't remember now whether I confirmed that the changes the original author made (to the upstream repo) fixed my original issue. Based on the original issue – in the GitHub project for the upstream repo – I was working on [the 2019 Advent of Code puzzles](https://adventofcode.com/2019); the relevant test module:

- [advent-of-code-2019/day_3_puzzle_2_test.exs at master · kenny-evitt/advent-of-code-2019](https://github.com/kenny-evitt/advent-of-code-2019/blob/master/test/advent_of_code_2019/day_3_puzzle_2_test.exs)

**Comment by nCrazed** [comment]
Ah shit, my bad. Followed trough here from the issue on the original 
repo without realizing that the repo changed.

**Comment by kenny-evitt** [comment]
@nCrazed No worries!
